//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaiveGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NaiveGUI.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright 的本地化字符串。
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Deleted] 的本地化字符串。
        /// </summary>
        public static string About_Misty {
            get {
                return ResourceManager.GetString("About_Misty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Special thanks to 的本地化字符串。
        /// </summary>
        public static string About_SpecialThanksTo {
            get {
                return ResourceManager.GetString("About_SpecialThanksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string AddRemote_Add {
            get {
                return ResourceManager.GetString("AddRemote_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string AddRemote_EditSave {
            get {
                return ResourceManager.GetString("AddRemote_EditSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Remote 的本地化字符串。
        /// </summary>
        public static string AddRemote_EditTitle {
            get {
                return ResourceManager.GetString("AddRemote_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote Name 的本地化字符串。
        /// </summary>
        public static string AddRemote_Name {
            get {
                return ResourceManager.GetString("AddRemote_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Padding 的本地化字符串。
        /// </summary>
        public static string AddRemote_Padding {
            get {
                return ResourceManager.GetString("AddRemote_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Remote 的本地化字符串。
        /// </summary>
        public static string AddRemote_Title {
            get {
                return ResourceManager.GetString("AddRemote_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote URI 的本地化字符串。
        /// </summary>
        public static string AddRemote_URI {
            get {
                return ResourceManager.GetString("AddRemote_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Log_Clear {
            get {
                return ResourceManager.GetString("Log_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Log_Save {
            get {
                return ResourceManager.GetString("Log_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        public static string Log_Title {
            get {
                return ResourceManager.GetString("Log_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete group {0} and {1} remotes inside it? 的本地化字符串。
        /// </summary>
        public static string Message_DeleteGroup {
            get {
                return ResourceManager.GetString("Message_DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must select a remote before starting listener! Click a remote in the remote list to select it. 的本地化字符串。
        /// </summary>
        public static string Message_NoRemote {
            get {
                return ResourceManager.GetString("Message_NoRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listener 的本地化字符串。
        /// </summary>
        public static string Proxy_Listener {
            get {
                return ResourceManager.GetString("Proxy_Listener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote 的本地化字符串。
        /// </summary>
        public static string Proxy_Remote {
            get {
                return ResourceManager.GetString("Proxy_Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Proxy_RemoteMenu_Add {
            get {
                return ResourceManager.GetString("Proxy_RemoteMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Proxy_RemoteMenu_Delete {
            get {
                return ResourceManager.GetString("Proxy_RemoteMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Proxy_RemoteMenu_Edit {
            get {
                return ResourceManager.GetString("Proxy_RemoteMenu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        public static string Proxy_RemoteMenu_Rename {
            get {
                return ResourceManager.GetString("Proxy_RemoteMenu_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy 的本地化字符串。
        /// </summary>
        public static string Proxy_Title {
            get {
                return ResourceManager.GetString("Proxy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow adding listener 的本地化字符串。
        /// </summary>
        public static string Settings_AllowAddListener {
            get {
                return ResourceManager.GetString("Settings_AllowAddListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow window resize 的本地化字符串。
        /// </summary>
        public static string Settings_AllowWindowResize {
            get {
                return ResourceManager.GetString("Settings_AllowWindowResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        public static string Settings_LanguageAuto {
            get {
                return ResourceManager.GetString("Settings_LanguageAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable logging 的本地化字符串。
        /// </summary>
        public static string Settings_Logging {
            get {
                return ResourceManager.GetString("Settings_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start on boot 的本地化字符串。
        /// </summary>
        public static string Settings_StartOnBoot {
            get {
                return ResourceManager.GetString("Settings_StartOnBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto update 的本地化字符串。
        /// </summary>
        public static string Subscription_AutoUpdate {
            get {
                return ResourceManager.GetString("Subscription_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscription 的本地化字符串。
        /// </summary>
        public static string Subscription_Title {
            get {
                return ResourceManager.GetString("Subscription_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interval: 的本地化字符串。
        /// </summary>
        public static string Subscription_UpdateInterval {
            get {
                return ResourceManager.GetString("Subscription_UpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated {0} subscription{1}. 的本地化字符串。
        /// </summary>
        public static string Subscription_UpdateNotification {
            get {
                return ResourceManager.GetString("Subscription_UpdateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Now 的本地化字符串。
        /// </summary>
        public static string Subscription_UpdateNow {
            get {
                return ResourceManager.GetString("Subscription_UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating 的本地化字符串。
        /// </summary>
        public static string Subscription_Updating {
            get {
                return ResourceManager.GetString("Subscription_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listener crashed, restarting... 的本地化字符串。
        /// </summary>
        public static string Tray_Crashed {
            get {
                return ResourceManager.GetString("Tray_Crashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listener crashed for too many times, manually maintenance required. 的本地化字符串。
        /// </summary>
        public static string Tray_CrashedTooMany {
            get {
                return ResourceManager.GetString("Tray_CrashedTooMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Listener Available 的本地化字符串。
        /// </summary>
        public static string Tray_NoListener {
            get {
                return ResourceManager.GetString("Tray_NoListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NaiveGUI - Running 的本地化字符串。
        /// </summary>
        public static string Tray_Running {
            get {
                return ResourceManager.GetString("Tray_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle 的本地化字符串。
        /// </summary>
        public static string Tray_Toggle {
            get {
                return ResourceManager.GetString("Tray_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Subscription Name\nName can&apos;t be duplicate 的本地化字符串。
        /// </summary>
        public static string YAAAY_1 {
            get {
                return ResourceManager.GetString("YAAAY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Subscription URL\n\nExample:\nhttps://www.google.com 的本地化字符串。
        /// </summary>
        public static string YAAAY_2 {
            get {
                return ResourceManager.GetString("YAAAY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the listening URI\n\nExample:\nsocks://0.0.0.0:1080\nhttp://127.0.0.1:8388 的本地化字符串。
        /// </summary>
        public static string YAAAY_3 {
            get {
                return ResourceManager.GetString("YAAAY_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input the new name.\nIf there&apos;s group with same name, they will be merged.\nItems with same name will be overrided! 的本地化字符串。
        /// </summary>
        public static string YAAAY_8 {
            get {
                return ResourceManager.GetString("YAAAY_8", resourceCulture);
            }
        }
    }
}
